In [1]:
import numpy as np 
import pandas as pd

In [5]:
df = pd.DataFrame([[8,8,9],[7,9,5],[6,10,6],[5,12,7]], columns = ['cgpa','profile_score','lpa'])

In [6]:
df

cgpa  profile_score  lpa
0     8              8    9
1     7              9    5
2     6             10    6
3     5             12    7

In [10]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [11]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

C:\Users\vaish\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.get_weights()

[array([[ 1.1152884 ,  0.4094422 ],
        [-0.45685107,  0.30072057]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.3795391 ],
        [ 0.84261405]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
              np.array([[1.3167752 ],[0.47065687]],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [20]:
model.set_weights(new_weights)

In [21]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.3167752 ],
        [0.47065687]], dtype=float32),
 array([0.], dtype=float32)]

In [28]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer='adam', loss='mean_squared_error')

In [29]:
# from tensorflow.keras import losses
# model.compile(optimizer='adam', loss=losses.MeanSquaredError())

In [30]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 2.0691  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0629
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0627 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.0543 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0447 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0428 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.0396 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0509 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.0378 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0470 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.0449 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2.0383
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.0351 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0413 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.0468
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━